### PR TITLE
Upgrade to NLog 4 + NuGet badge

### LINKED ISSUE #18: Build to NLog 4
Is see the plugin is build to an old version of NLog. I would recommend to build this to NLog 4.0.0. 

Since NLog 4.0.0 the assembly version is stable so you can use NLog 4.x.y without any assembly redirect.

### PR DESCRIPTION
**Pull request by 304NotModified**
I also upgrade the nuspec version - but no problem if you change the version number to something else.

I didn't run the unit tests, yet. Dunno how. 

fixes #18

### CODE REVIEW

**Comment by 304NotModified** [comment]
image

image

**Comment by rho24** [comment]
Awesome:) I'll merge and deploy as soon as I can!

Thanks very much

**Comment by 304NotModified** [comment]
PS: I added also a NuGet badge (was not intended in this PR, but forgot to create branches)

**Comment by 304NotModified** [comment]
Any idea when it get's deployed?

**Comment by rho24** [comment]
Sorry for the delay, finally found some time this morning. Just waiting for the build to go through and then i'll pump it up to nuget.
Thanks very much for the PR! :smile:

**Comment by rho24** [comment]
Now up on nuget

**Pull request merged**
