### PR TITLE
Can now show objects in Message

### PR DESCRIPTION
**Pull request by sorenml**
Can not show exceptions and objects in Message, e.g.
logger.Debug(new {
message = "Check out this object",
data = new List<string>() {
"Code A",
"Code B",
"Code C",
},
count = 3
});

### CODE REVIEW

**Comment by rho24** [comment]
Looks good to me! I'll get a release out as soon as i can.

Don't suppose you'd like to extend the client side filtering to work with objects too would you? Of the top of my head checking if its an object and if so JSON.stringify ing it before filtering should work.

**Comment by rho24** [comment]
A new package will be out once appveyor is back up.

Thanks again for the contribution!

**Comment by rho24** [comment]
Package live

**Comment by sorenml** [comment]
Great :) Thank you

**Pull request merged**
